---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Kibana.
  package: name=kibana state=present

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: started
    enabled: yes

- name: Copy Kibana SSL key
  become: yes
  copy:
    content: "{{ kibana_server_ssl_key }}"
    dest: "/etc/kibana/kibana_server_ssl.key"
    owner: kibana
    group: kibana
    mode: 0600
  notify: restart kibana
  when: kibana_server_ssl_key is defined

- name: Copy Kibana SSL certificate
  become: yes
  copy:
    content: "{{ kibana_server_ssl_certificate }}"
    dest: "/etc/kibana/kibana_server_ssl.crt"
    owner: kibana
    group: kibana
    mode: 0644
  notify: restart kibana
  when: kibana_server_ssl_certificate is defined

- name: Copy Kibana configuration.
  template:
    src: kibana.yml.j2
    dest: "/opt/kibana/config/kibana.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana
